config/routes.rb
Rails.application.routes.draw do

	root 'pages#index', as: 'home' 
	get 'products' => 'products#products'
	get 'contact' => 'pages#contact'
	post 'contact' => 'pages#contact'
	post 'create_contact' => 'pages#create'
	get 'product_description' => 'products#product_description'

 
	resources :pages

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
    validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
    validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index

		@title = 'About us'
		@content = 'This is the landing page'
		
	end

	def contact
		@title = 'Contact us'	
	end

	def create
		contact = Contact.new(contact_params)
		if contact.save	
			redirect_to home_path
		else
			flash[:errors] = contact.errors.full_messages
			redirect_to contact_path
		end
	end

	private
	def contact_params
		params.require(:contact).permit(:email)
		
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def products
		@title = 'Products'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestingSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>

    <%= link_to 'Home', home_path %>
	  <%= link_to 'Products', products_path %>
	  <%= link_to 'Contact', contact_path %>

    <%= yield %>
    
  </body>
</html>

app/views/pages/contact.html.erb
<h1><%= @title%></h1>
 
<% if flash[:errors] %>
	<% flash[:errors].each do |e| %>
		<p><%= e %></p>
	<%end%>
<%end%>

<%= form_for :contact, url: create_contact_path, :html => { :id => "email_form" } do |f| %>

	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>

	<p><%= f.submit "Submit" %></p>
<% end %>

app/views/pages/index.html.erb
<h1><%= @title %></h1>
<p><%= @content%></p>

app/views/products/product_description.html.erb
<h1>Product Description</h1>
<h3>Product complete description</h3>

app/views/products/products.html.erb
<h1><%= @title%></h1>
<h3>Product 1</h3>
<p>Product brief description</p>
<%= link_to 'Read more', product_description_path %>